apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-deployment
  labels:
    app: quarkus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quarkus
  template:
    metadata:
      labels:
        app: quarkus
    spec:
      containers:
        - name: quarkus
          image: ajayk297/quarkus-example:latest
          imagePullPolicy: IfNotPresent #can set Always & Never as well
          env:
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgresql-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgresql-pwd
            - name: POSTGRESQL_DATABASE
              value: quarkus
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: postgresql-url
          ports:
            - containerPort: 8080
---
#service
apiVersion: v1
kind: Service
metadata:
  name: quarkus-service
spec:
  type: NodePort
  selector:
    app: quarkus
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100


